### ISSUE TITLE
7 pin cable length

### ISSUE THREAD

**Issue by fi0** [JesusFreke/lalboard#4]
I found a source for 7-pin silicone wire with ZH 1.5. How long should I buy? is 6" long enough?

**Comment by JesusFreke** [comment]
See https://github.com/JesusFreke/lalboard/wiki/BOM. You'll want 10x of the 6" ones, and one longer one. The longer one is the one that runs between the two sides. I would say probably a minimum of 10" for that one, but 12" or even longer may be better. The longer it is the further apart you can have the 2 sides, of course. I think mine is maybe something like 18" or so. I didn't really measure it precisely.

**Comment by JesusFreke** [comment]
Also, care to share the source? :) I can add it to the BOM page

**Comment by HeuristicBishop** [comment]
I would also greatly appreciate a source!

**Comment by fi0** [comment]
Thank you for the clarifications! I'm going to place a custom order from a factory in China.

**Comment by HeuristicBishop** [comment]
Not the cheapest in the world but non-silicon premade jumpers can be sourced from digi-key:
Part number: A07ZR07ZR28H102B

**Comment by JesusFreke** [comment]
Yeah, the BOM includes links to at least some 150mm cables with PVC insulation. I found a similar 1'/300mm digikey cable and added a link to the BOM.

They'll definitely work, but it's a bit of a pain working with them in such a confined space.

I wasn't familiar with the ZR line. It looks like they're a "press in" connector, that is compatible with the ZH sockets. Interesting. They may be significantly quicker and easier to use when making your own cables, since you don't have painstakingly crimp each individual wire twice. I'll have to try them out.
